/* GENERATED by control_profile_codegen.py; do not edit. */
#ifndef PLUTO_CONTROL_PROFILE_H
#define PLUTO_CONTROL_PROFILE_H
#include <stdint.h>

#define CONTROL_PROFILE_ID "fast20-v1"
#define CONTROL_PROFILE_REVISION 1u
#define CONTROL_PROFILE_CONTRACT_SHA256 "25b2bd0769687cc255d5e6926312e7e827672dc4567d64aecd85e8078acb4258"
#define CONTROL_ALL_OFF_CODE 0x8u
#define CONTROL_GUARD_MS 5u
#define CONTROL_MARKER_BODY_MS 80u
#define CONTROL_STATE_COUNT 8u
#define CONTROL_NOMINAL_CYCLE_MS 386u

typedef struct { uint8_t gpio_code_pa3_pa0; uint16_t dwell_ms; } control_step_t;
static const control_step_t CONTROL_SCHEDULE[CONTROL_STATE_COUNT] = {
  { 0x0u, 20u }, /* ANT1 */
  { 0x4u, 23u }, /* ANT2 */
  { 0x2u, 26u }, /* ANT3 */
  { 0x6u, 30u }, /* ANT4 */
  { 0x1u, 34u }, /* ANT5 */
  { 0x5u, 39u }, /* ANT6 */
  { 0x3u, 44u }, /* ANT7 */
  { 0x7u, 50u }, /* ANT8 */
};

#endif
