/* GENERATED by generate_phase20_profile.py; do not edit. */
#ifndef PLUTO_PHASE20_CONTROL_PROFILE_H
#define PLUTO_PHASE20_CONTROL_PROFILE_H
#include <stdint.h>

#define CONTROL_PROFILE_ID "phase20-v1"
#define CONTROL_PROFILE_REVISION 1u
#define CONTROL_PROFILE_CONTRACT_SHA256 "988dc5012b8ec4e931f528d054fa7b45248ce38d9d65c9b1ebba12b1de61c6e0"
#define CONTROL_ALL_OFF_CODE 0x8u
#define CONTROL_GUARD_MS 5u
#define CONTROL_MARKER_BODY_MS 20u
#define CONTROL_STATE_COUNT 8u
#define CONTROL_NOMINAL_CYCLE_MS 220u

typedef struct { uint8_t gpio_code_pa3_pa0; uint16_t dwell_ms; } control_step_t;
static const control_step_t CONTROL_SCHEDULE[CONTROL_STATE_COUNT] = {
  { 0x0u, 20u }, /* ANT1 */
  { 0x4u, 20u }, /* ANT2 */
  { 0x2u, 20u }, /* ANT3 */
  { 0x6u, 20u }, /* ANT4 */
  { 0x1u, 20u }, /* ANT5 */
  { 0x5u, 20u }, /* ANT6 */
  { 0x3u, 20u }, /* ANT7 */
  { 0x7u, 20u }, /* ANT8 */
};

#endif
