/* GENERATED by generate_tracking_c6_profiles.py; do not edit. */
#ifndef PLUTO_TRACKING_C6_CONTROL_PROFILE_H
#define PLUTO_TRACKING_C6_CONTROL_PROFILE_H
#include <stdint.h>

#define CONTROL_PROFILE_ID "tracking-c6-1000us-v1"
#define CONTROL_PROFILE_REVISION 1u
#define CONTROL_PROFILE_CONTRACT_SHA256 "05bc7389236717bc63cde4b9653e588bcf8cef5d535900d3b6be4ca603a69f78"
#define CONTROL_EXPERIMENTAL_GUARD_WAIVER 1u
#define CONTROL_RELEASED_GUARD_US 5000u
#define CONTROL_ALL_OFF_CODE 0x8u
#define CONTROL_TIMER_HZ 1000000u
#define CONTROL_GUARD_US 20u
#define CONTROL_MARKER_BODY_US 180u
#define CONTROL_MAX_LATENESS_US 5u
#define CONTROL_STATE_COUNT 6u
#define CONTROL_NOMINAL_CYCLE_US 6300u

typedef struct { uint8_t gpio_code_pa3_pa0; uint16_t dwell_us; } control_step_us_t;
static const control_step_us_t CONTROL_SCHEDULE[CONTROL_STATE_COUNT] = {
  { 0x0u, 1000u }, /* ANT1 */
  { 0x4u, 1000u }, /* ANT2 */
  { 0x6u, 1000u }, /* ANT4 */
  { 0x7u, 1000u }, /* ANT8 */
  { 0x3u, 1000u }, /* ANT7 */
  { 0x1u, 1000u }, /* ANT5 */
};

#define CONTROL_LONG_CONTROL_REFRESH_OPPORTUNITIES 2u
#endif
