/* GENERATED by generate_hexcal_profile.py; do not edit. */
#ifndef PLUTO_HEXCAL_CONTROL_PROFILE_H
#define PLUTO_HEXCAL_CONTROL_PROFILE_H
#include <stdint.h>

#define CONTROL_PROFILE_ID "hexcal-v1"
#define CONTROL_PROFILE_REVISION 1u
#define CONTROL_PROFILE_CONTRACT_SHA256 "06324954fb43710af89f6f9e439a7d4bf652c18de714e56645d71f8099689726"
#define CONTROL_EXPERIMENTAL_GUARD_WAIVER 1u
#define CONTROL_RELEASED_GUARD_US 5000u
#define CONTROL_ALL_OFF_CODE 0x8u
#define CONTROL_TIMER_HZ 1000000u
#define CONTROL_GUARD_US 20u
#define CONTROL_MARKER_BODY_US 180u
#define CONTROL_MAX_LATENESS_US 5u
#define CONTROL_STATE_COUNT 6u
#define CONTROL_NOMINAL_CYCLE_US 1500u

typedef struct { uint8_t gpio_code_pa3_pa0; uint16_t dwell_us; } control_step_us_t;
static const control_step_us_t CONTROL_SCHEDULE[CONTROL_STATE_COUNT] = {
  { 0x0u, 200u }, /* ANT1 */
  { 0x4u, 200u }, /* ANT2 */
  { 0x2u, 200u }, /* ANT3 */
  { 0x6u, 200u }, /* ANT4 */
  { 0x1u, 200u }, /* ANT5 */
  { 0x5u, 200u }, /* ANT6 */
};

#endif
