/* GENERATED by generate_tracking_c6_profiles.py; do not edit. */
#ifndef PLUTO_TRACKING_C6_CONTROL_PROFILE_H
#define PLUTO_TRACKING_C6_CONTROL_PROFILE_H
#include <stdint.h>

#define CONTROL_PROFILE_ID "tracking-c6-25us-v1"
#define CONTROL_PROFILE_REVISION 1u
#define CONTROL_PROFILE_CONTRACT_SHA256 "649d3b565fab0afbc0b3ab7c191aa3a1d7a70870b070910f8959b4638232bbb2"
#define CONTROL_EXPERIMENTAL_GUARD_WAIVER 1u
#define CONTROL_RELEASED_GUARD_US 5000u
#define CONTROL_ALL_OFF_CODE 0x8u
#define CONTROL_TIMER_HZ 1000000u
#define CONTROL_GUARD_US 20u
#define CONTROL_MARKER_BODY_US 180u
#define CONTROL_MAX_LATENESS_US 5u
#define CONTROL_STATE_COUNT 6u
#define CONTROL_NOMINAL_CYCLE_US 450u

typedef struct { uint8_t gpio_code_pa3_pa0; uint16_t dwell_us; } control_step_us_t;
static const control_step_us_t CONTROL_SCHEDULE[CONTROL_STATE_COUNT] = {
  { 0x0u, 25u }, /* ANT1 */
  { 0x4u, 25u }, /* ANT2 */
  { 0x6u, 25u }, /* ANT4 */
  { 0x7u, 25u }, /* ANT8 */
  { 0x3u, 25u }, /* ANT7 */
  { 0x1u, 25u }, /* ANT5 */
};

#endif
